name: Frontend workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test JS frontend
    defaults:
      run:
        working-directory: ./web
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install requirements
      run: npm install
    - name: Run tests and collect coverage
      run: npm run test
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true # optional (default = false)
        # files: ./coverage/clover.xml
        # flags: unittests # optional
        # name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)
